name: Build and run benchmarks

on:
  push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Debug
            flags: platform=linuxbsd target=editor optimize=debug module_mono_enabled=no progress=no debug_symbols=yes
            archive: debug.tar
            type: debug
            gdextension: template_debug
            bin: godot.linuxbsd.editor.x86_64

          - name: Release
            flags: platform=linuxbsd target=template_release optimize=speed lto=full module_mono_enabled=no progress=no debug_symbols=yes disable_path_overrides=no
            archive: release.tar
            type: release
            gdextension: template_release
            bin: godot.linuxbsd.template_release.x86_64

    steps:
      - name: Workaround actions/upload-artifact#176
        run: echo "ARTIFACTS_PATH=$(realpath ..)" >> $GITHUB_ENV

      - name: Checkout benchmarks
        uses: actions/checkout@v7
        with:
          path: benchmarks
          submodules: recursive

      - name: Checkout godot
        uses: actions/checkout@v7
        with:
          repository: godotengine/godot
          path: godot

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb mesa-vulkan-drivers

      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          architecture: x64

      - name: Setup SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons==4.10.1
          scons --version

      - name: Force remove preinstalled .NET SDKs
        run: |
          sudo rm -rf /usr/share/dotnet/sdk/*

      - name: Setup older .NET SDK as baseline
        uses: actions/setup-dotnet@v5
        with:
          # Targeting the oldest version we want to support to ensure it still builds.
          dotnet-version: 8.0.100

      - name: Install mold linker
        uses: rui314/setup-mold@v1

      - name: Build ${{ matrix.name }}
        working-directory: godot
        shell: bash
        run: |
          Xvfb :0 -screen 0 1024x768x24 &
          echo "scons ${{ matrix.flags }}"
          BEGIN="$(date +%s%3N)"
          PEAK_MEMORY_BUILD=$( (/usr/bin/time -f "%M" scons ${{ matrix.flags }} 2>&1 || true) | tail -1)
          END="$(date +%s%3N)"
          TIME_TO_BUILD="$((END - BEGIN))"
          jq -Rs "." <<< '{ "time": $TIME_TO_BUILD }' > ${{ env.ARTIFACTS_PATH }}/buildtime_${{ matrix.type }}.json
          jq -Rs "." <<< '{ "ram_bytes": $PEAK_MEMORY_BUILD }' > ${{ env.ARTIFACTS_PATH }}/buildram_${{ matrix.type }}.json

      - name: Archive build
        working-directory: godot/bin
        shell: bash
        run: |
          tar -cvf ${{ env.ARTIFACTS_PATH }}/${{ matrix.archive }} ${{ matrix.bin }}
          tar -rf ${{ env.ARTIFACTS_PATH }}/${{ matrix.archive }} ${{ env.ARTIFACTS_PATH }}/*.json

      - name: Build gdextension
        working-directory: benchmarks/gdextension
        shell: bash
        run: scons target=${{ matrix.gdextension }}

      - name: Archive gdextension
        working-directory: benchmarks/gdextension/bin
        shell: bash
        run: tar -cvf ${{ env.ARTIFACTS_PATH }}/${{ matrix.gdextension }}.tar *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}
          path: ${{ env.ARTIFACTS_PATH }}/${{ matrix.archive }}
          retention-days: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.gdextension }}.tar
          path: ${{ env.ARTIFACTS_PATH }}/${{ matrix.gdextension }}.tar
          retention-days: 1

  benchmarks:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Debug warmup
            type: debug
            bin: godot.linuxbsd.editor.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: warmup
            archive: warmup_debug.tar

          - name: Release warmup
            type: release
            bin: godot.linuxbsd.template_release.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: warmup
            archive: warmup_release.tar

          - name: Debug memory
            type: debug
            bin: godot.linuxbsd.editor.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: memory
            archive: memory_debug.tar

          - name: Release memory
            type: release
            bin: godot.linuxbsd.template_release.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: memory
            archive: memory_release.tar

          - name: Debug shader cache
            type: debug
            bin: godot.linuxbsd.editor.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: cache
            archive: cache_debug.tar

          - name: Debug cpu
            type: debug
            bin: godot.linuxbsd.editor.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: cpu
            archive: cpu_debug.tar

          - name: Release cpu
            type: release
            bin: godot.linuxbsd.template_release.x86_64
            editor: godot.linuxbsd.editor.x86_64
            test: cpu
            archive: cpu_release.tar

    steps:
      - name: Workaround actions/upload-artifact#176
        run: echo "ARTIFACTS_PATH=$(realpath ..)" >> $GITHUB_ENV

      - name: Checkout benchmarks
        uses: actions/checkout@v7
        with:
          path: benchmarks
          submodules: recursive

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.type }}.tar
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Download build
        if: ${{ matrix.type != 'debug' }}
        uses: actions/download-artifact@v4
        with:
          name: debug.tar
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Download gdextension build
        uses: actions/download-artifact@v4
        with:
          name: template_debug.tar
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Download gdextension build
        uses: actions/download-artifact@v4
        with:
          name: template_release.tar
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Prepare environment
        run: mkdir -p ${{ env.ARTIFACTS_PATH }}/bin

      - name: Extract build
        working-directory: ${{ env.ARTIFACTS_PATH }}/bin
        run: tar -xvf ${{ env.ARTIFACTS_PATH }}/${{ matrix.type }}.tar

      - name: Extract editor build
        if: ${{ matrix.type != 'debug' }}
        working-directory: ${{ env.ARTIFACTS_PATH }}/bin
        run: tar -xvf ${{ env.ARTIFACTS_PATH }}/debug.tar

      - name: Extract gdextension
        working-directory: benchmarks/gdextension/bin
        run: |
          tar -xvf ${{ env.ARTIFACTS_PATH }}/template_debug.tar
          tar -xvf ${{ env.ARTIFACTS_PATH }}/template_release.tar

      - name: Warmup run
        shell: bash
        working-directory: benchmarks/web/godot-empty-project
        run: ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.bin }} --audio-driver Dummy --gpu-index 1 --quit || true

      - name: Benchmark warmup
        if: ${{ matrix.test == 'warmup' }}
        shell: bash
        working-directory: benchmarks/web/godot-empty-project
        run: |
          TOTAL=0
          for _ in {0..19}; do
            BEGIN="$(date +%s%3N)"
            echo "Performing benchmark debug startup/shutdown run."
            ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.bin }} --audio-driver Dummy --gpu-index 1 --quit || true
            END="$(date +%s%3N)"
            TOTAL="$((TOTAL + END - BEGIN))"
          done
          TIME_TO_STARTUP_SHUTDOWN="$((TOTAL / 20))"
          jq -Rs "." <<< '{ "time": $TIME_TO_STARTUP_SHUTDOWN }' > ${{ env.ARTIFACTS_PATH }}/startuptime.json

      - name: Benchmark peak memory startup
        if: ${{ matrix.test == 'memory' }}
        shell: bash
        working-directory: benchmarks/web/godot-empty-project
        run: |
          PEAK_MEMORY_STARTUP_SHUTDOWN=$(/usr/bin/time -f "%M" ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.bin }} --audio-driver Dummy --gpu-index 1 --quit 2>&1 | tail -1)
          jq -Rs "." <<< '{ "time": $PEAK_MEMORY_STARTUP_SHUTDOWN }' > ${{ env.ARTIFACTS_PATH }}/memory.json

      - name: Benchmark shader cache
        if: ${{ matrix.test == 'cache' }}
        shell: bash
        working-directory: benchmarks/web/godot-empty-project
        run: |
          BEGIN="$(date +%s%3N)"
          ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.editor }} -e --audio-driver Dummy --gpu-index 1 --quit || true
          END="$(date +%s%3N)"
          TOTAL="$((END - BEGIN))"
          jq -Rs "." <<< '{ "time": $TOTAL }' > ${{ env.ARTIFACTS_PATH }}/cache.json

      - name: Benchmark no shader cache
        if: ${{ matrix.test == 'cache' }}
        shell: bash
        working-directory: benchmarks/web/godot-empty-project
        run: |
          TOTAL=0
          for _ in {0..9}; do
            BEGIN="$(date +%s%3N)"
            echo "Performing benchmark shader cache debug editor run."
            ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.editor }} -e --audio-driver Dummy --gpu-index 1 --quit || true
            END="$(date +%s%3N)"
            TOTAL="$((TOTAL + END - BEGIN))"
          done
          TIME_TO_STARTUP_SHADER_CACHE="$((TOTAL / 10))"
          jq -Rs "." <<< '{ "time": $TIME_TO_STARTUP_SHADER_CACHE }' > ${{ env.ARTIFACTS_PATH }}/nocache.json

      - name: Benchmark cpu
        if: ${{ matrix.test == 'cpu' }}
        shell: bash
        working-directory: benchmarks
        run: |
          ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.editor }} --headless --import --gpu-index 1 --build-solutions --quit-after 2
          set +e # disable failing on error, the engine may crash after successfully running benchmarks
          ${{ env.ARTIFACTS_PATH }}/bin/${{ matrix.bin }} --audio-driver Dummy --gpu-index 1 -- --run-benchmarks --exclude-benchmarks="rendering/*" --save-json="${{ env.ARTIFACTS_PATH }}/cpu_${{ matrix.type }}.json" --json-results-prefix="cpu_${{ matrix.type }}" || {
            echo "${{ matrix.bin }} crashed?"
            true
          }

      - name: Archive results
        shell: bash
        run: |
          cp ${{ env.ARTIFACTS_PATH }}/bin/*.json ${{ env.ARTIFACTS_PATH }}/
          tar -cvf ${{ matrix.archive }} ${{ env.ARTIFACTS_PATH }}/*.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}
          retention-days: 1
