name: Run benchmarks

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Run benchmarks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v7
        with:
          path: benchmarks

      - name: Checkout godot
        uses: actions/checkout@v7
        repository: godotengine/godot
        with:
          path: godot

      - name: Checkout website
        uses: actions/checkout@v7
        repository: shana/godot-benchmarks-results
        with:
          path: results

      - name: Run the run-benchmarks-github.sh script
        working-directory: benchmarks
        run: |
          ./run-benchmarks-github.sh
