name: Run benchmarks

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Run benchmarks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run the run-benchmarks.sh script
        run: |
          ./run-benchmarks.sh
